name = "zoko-stream"
main = "worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# routes = [
#   { pattern = "zoko.anixo.online", custom_domain = true }
# ]

# Cloudflare KV Cache Binding (Included in $5/mo Paid Plan)
[[kv_namespaces]]
binding = "ZOKO_CACHE"
id = "623d55da187542a39fd13af3eaa4ad3a"

# Enable Cloudflare Edge Observability & Real-Time Logs
[observability]
enabled = true

[vars]
TURNSTILE_SECRET_KEY = "0x4AAAAAADGQxcZgLa0ZRtaJbL3mxiKj4RA"
