name = "animesky-api"
main = "index.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [
  { pattern = "hindi.anixo.online/*", zone_name = "anixo.online" }
]

# Smart Placement (executes worker closest to upstream data sources)
[placement]
mode = "smart"

# Cloudflare KV Cache (Included in $5/mo Paid Plan: 10M reads, 1M writes)
[[kv_namespaces]]
binding = "ANIMESKY_CACHE"
id = "b77a4adff5014a8d89516a290add396a"

[assets]
directory = "./public"
binding = "ASSETS"

[observability]
enabled = true
