name = "aniko-backend"
main = "worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
# Cloudflare KV Cache Binding (Paid Plan High Speed Cache)
[[kv_namespaces]]
binding = "ANIKO_CACHE"
id = "c4366e9838794cff8a196de5a5e32840"

# Enable Cloudflare Edge Observability & Logs
[observability]
enabled = true

[vars]
TURNSTILE_SECRET_KEY = "0x4AAAAAADGQxcZgLa0ZRtaJbL3mxiKj4RA"
