name = "vidcloud-embed"
main = "worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

workers_dev = true

# Custom Domain for vidcloud.sbs
# routes = [
#   { pattern = "vidcloud.sbs/*", zone_name = "vidcloud.sbs" },
#   { pattern = "vidcloud.sbs", custom_domain = true }
# ]

[placement]
mode = "smart"

[observability]
enabled = true

# Persistent Cloudflare KV Database for Admin Config, Firewall, and Keys
[[kv_namespaces]]
binding = "VIDCLOUD_ADMIN_STORE"
id = "0d6952975eeb4eea96fa8f4f78c03f14"

[vars]
TURNSTILE_SECRET_KEY = "0x4AAAAAADGQxcZgLa0ZRtaJbL3mxiKj4RA"
TURNSTILE_SITE_KEY = "0x4AAAAAADGQxfMRQroxFG6O"
UPSTREAM_PLAYER = "https://player.anixo.online"
PLAYER_ORIGIN = "https://vidcloud.sbs/player"
